version: '3.8'

services:
  # dbname: openmrs username: openmrs pw: openmrs rootpw: openmrs
  omrsdb:
    image: mariadb:10.11.7
    restart: "unless-stopped"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"
    healthcheck:
      test: "mysql --user=openmrs --password=openmrs --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: openmrs
      MYSQL_ROOT_PASSWORD: openmrs
    volumes:
      - ./omrs-db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  sqlmesh-db:
    image: mariadb:10.11.7
    restart: "unless-stopped"
    command: "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_USER: openmrs
      MYSQL_PASSWORD: openmrs
      MYSQL_ROOT_PASSWORD: openmrs
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  core:
    build: core
    image: omop-etl-core
    container_name: core
    environment:
      SRC_HOST: omrsdb
      SRC_PORT: 3306
      SRC_USER: openmrs
      SRC_PASS: openmrs
      SRC_DB: openmrs
      SQLMESH_DB_ROOT_PASSWORD: openmrs
      TARGET_HOST: omop-db
      TARGET_PORT: 5432
      TARGET_USER: omop
      TARGET_PASS: omop
      TARGET_DB: omop
      ACHILLES_VOCAB_SCHEMA: vocab
      ACHILLES_RESULTS_SCHEMA: results
    depends_on:
      - sqlmesh-db
      - omrsdb
    ports:
      - "8000:8000"

    volumes:
      # Uncomment the following line during development to mount local files and see changes without rebuilding the image.
      # Note: This will override files copied into /core during build.
      # - so be sure your local files are complete.
       - ./core:/core
    profiles:
      - manual

volumes:
  db-data: ~
  postgres_data: ~
  jdbc-drivers-data: ~
  cdm-postprocessing-data: ~
